
services:

  frontend:
    build:
      context: ./front-end
      dockerfile: dockerfile
    ports:
      - "3500:80"
    volumes:
      - ./front-end:/app
    stdin_open: true
    tty: true


networks:
  mern_network:
