version: '3.9'
services:
  backend:
    build:
      context: ./back-end
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back-end:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/quiz
    depends_on:
      - mongo

  frontend:
    build:
      context: ./front-end
      dockerfile: dockerfile
    ports:
      - "3500:80"
    volumes:
      - ./front-end:/app
    stdin_open: true
    tty: true

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8070:8080"  
      - "50001:50000" 
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

      - JAVA_HOME= C:\Program Files\Java\jdk-21
      - JAVA_OPTS="-Dfile.encoding=UTF-8"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./jenkins-docker-certs:/certs/client:ro
      - ./back-end:/var/jenkins_home/workspace/back-end
      - ./front-end:/var/jenkins_home/workspace/front-end
      - ./functional-tests:/var/jenkins_home/workspace/functional-tests
    networks:
      - mern_network
    restart: unless-stopped 



volumes:
  mongo_data:
  jenkins-data:

networks:
  mern_network:

#tesm