# Usa una imagen base de Node.js para construir la app
FROM node:16 AS build

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de configuración
COPY package*.json ./

# Instala las dependencias
RUN npm install --legacy-peer-deps

# Copia el resto del código
COPY . .

# Construye la aplicación
RUN npm run build

# Usa una imagen ligera para servir la app
FROM nginx:alpine

# Copia los archivos construidos
COPY --from=build /app/build /usr/share/nginx/html

# Expone el puerto del frontend
EXPOSE 80

# Comando para iniciar NGINX
CMD ["nginx", "-g", "daemon off;"]

