# Usa una imagen base de Node.js
FROM node:16-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto del backend
EXPOSE 5000

# Comando para iniciar el servidor
CMD ["node", "server.js"]

