jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Agregar permisos de ejecución al script
      - name: Set execute permissions for custom build script
        run: chmod +x front-end/oryx-build.sh

      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "front-end"
          api_location: ""
          output_location: "front-end/build"
          skip_app_build: true # ⬅️ Evita que Oryx haga `npm install` automáticamente
          custom_build_command: "./oryx-build.sh" # ⬅️ Usa el script personalizado
