name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      # 🏗️ Build y Deploy de quiz-1 (front-end)
      - name: Install Dependencies (quiz-1)
        run: |
          cd front-end
          npm install --legacy-peer-deps

      - name: Build quiz-1
        run: |
          cd front-end
          export CI=false 
          npm run build --legacy-peer-deps

      - name: Deploy quiz-1
        id: deploy_quiz1
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN_QUIZ1 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "front-end"
          output_location: "front-end/build"

      # 🏗️ Build y Deploy de quiz-2
      - name: Install Dependencies (quiz-2)
        run: |
          cd quiz-2
          npm install --legacy-peer-deps

      - name: Build quiz-2
        run: |
          cd quiz-2
          export CI=false 
          npm run build --legacy-peer-deps

      - name: Deploy quiz-2
        id: deploy_quiz2
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN_QUIZ2 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "quiz-2"
          output_location: "quiz-2/build"
